baseURL = "http://gobacktest.github.io/"
languageCode = "en-us"
title = "gobacktest"
theme = "github.com/alex-shpak/hugo-book"

# Book configuration
disablePathToLower = false
enableGitInfo = true

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ['taxonomy', 'taxonomyTerm']

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]
# [[menu.before]]
[[menu.after]]
  name = "View on Github"
  url = "https://github.com/gobacktest/gobacktest"
  weight = 10

# see https://themes.gohugo.io/hugo-book/ for options
[params]
  BookTheme = 'auto'
  BookToC = true
  # BookLogo = 'logo.png'
  BookSection = 'docs'
  BookRepo = 'https://github.com/gobacktest/gobacktest.github.io'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main/content'

  # (Optional, default January 2, 2006) Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat = '02.01.2006'